set encoding=utf-8
colorscheme candle-grey-transparent
set guifont=Cascadia_Mono:h24
set t_Co=256
syntax on
set spell spelllang=en_us
set showmatch
set nocompatible
set autoindent
set smartindent
set number relativenumber
set tabstop=4 shiftwidth=4
set expandtab
set textwidth=120
set cursorcolumn
set cursorline
set ruler
set cindent
set cino=g0
set wildmenu
set showfulltag
set hlsearch
set incsearch
set ignorecase smartcase
set autoread
set backspace=indent,eol,start

filetype indent on
filetype plugin on
filetype plugin indent on

function! InitLspPlugins()
    call plug#begin()
    Plug 'tpope/vim-surround'
    Plug 'preservim/nerdtree'
    Plug 'junegunn/goyo.vim'
    Plug 'jreybert/vimagit'
    Plug 'vimwiki/vimwiki'
    Plug 'vim-airline/vim-airline'
    Plug 'ap/vim-css-color'
    Plug 'prabirshrestha/vim-lsp'
    Plug 'mattn/vim-lsp-settings'
    Plug 'dense-analysis/ale'
    Plug 'rhysd/vim-lsp-ale'
    call plug#end()
endfunction

call InitLspPlugins()

function! OnLspBufferEnabled() abort
    setlocal omnifunc=lsp#complete
    setlocal signcolumn=yes
endfunction

augroup lsp_install
    au!
    autocmd User lsp_buffer_enabled call OnLspBufferEnabled()
augroup END

autocmd FileType c,cpp,cc,go setlocal colorcolumn=120

highlight ColorColumn ctermbg=grey guibg=#ffffff

let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 25

nnoremap <leader>e :Explore<CR>
nnoremap <leader>s :Sexplore<CR>
